### ISSUE TITLE
Another project for CSV-to-YNAB conversion

### ISSUE THREAD

**Issue by torbengb** [milenvoutchev/2ynab#2]
Hello!
I've seen that you added a YNAB repository to GitHub. Have you seen that there are already many similar projects? There is one in particular that could be very interesting for you: "bank2ynab"

https://github.com/torbengb/bank2ynab/blob/develop/README.md

If you could provide a sample CSV export (anonymized) then we could easily create the converter for your bank, too! We already have DKB covered, and we are nearly done with Deutsche Bank as well, so your help would be fantastic: https://github.com/torbengb/bank2ynab/issues/131
--> Can you tell me the default file name when you download a CSV file from the bank?

Let me know what you think!
Best regards from snowy Austria,
Ben

**Comment by torbengb** [comment]
Hello! Just a kind reminder, if you don't mind. Would really appreciate to know the default file name.
Thanks - Ben

**Comment by milenvoutchev** [comment]
Hey there @torbengb , sorry I didn't get any notifications for this thread!
I wasn't aware of https://github.com/torbengb/bank2ynab/ but will definitely check it out!
I'm currently using DKB and DeutscheBank with the following filename conventions:
DKB Kreditkarte: 4748________1234.csv (first and last 4-digit groups of CC number)
DKB Girokonto: 1056351234.csv (last 8 digits of IBAN)
DeutscheBank Girokonto: Transactions_123_012345600_20180523_123456.csv (branch, account, date, last digit group - unidentified)
DeutscheBank Kreditkarte: CreditCardTransactions5232123412341234_2018_05.csv (card number, year, month)
Hope this helps! 
Please tag my username if commenting in the future, hopefully I'll receive notification :)

**Comment by torbengb** [comment]
@milenvoutchev thank you for this!
